// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Função para limpar e validar as chaves do Supabase vindas do ambiente
const cleanEnvVar = (value: string | undefined) => {
  if (!value) return "";
  // Remove aspas, espaços e barras finais que podem vir de erros de configuração no deploy
  return value.replace(/['"]+/g, "").trim().replace(/\/$/, "");
};

const SUPABASE_URL = cleanEnvVar(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = cleanEnvVar(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Verificação de segurança para evitar erro de inicialização silencioso
if (typeof window !== "undefined") {
  console.log("Supabase Client: Inicializando...");
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error("ERRO CRÍTICO: Chaves do Supabase não encontradas. Verifique as Environment Variables no painel de deploy.");
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});