// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Função para limpar e validar as chaves do Supabase vindas do ambiente
const cleanEnvVar = (value: string | undefined) => {
  if (!value) return "";
  // Remove aspas, espaços e barras finais que podem vir de erros de configuração no deploy
  return value.replace(/['"]+/g, "").trim().replace(/\/$/, "");
};

const SUPABASE_URL = cleanEnvVar(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = cleanEnvVar(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Diagnóstico detalhado de produção (parcialmente mascarado)
const maskValue = (val: string) => val ? `${val.substring(0, 10)}...${val.substring(val.length - 4)}` : "indefinido";

if (typeof window !== "undefined") {
  console.log("Supabase Client Init:");
  console.log("- URL:", maskValue(SUPABASE_URL));
  console.log("- Key (prefixo):", SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.substring(0, 15) : "ausente");
  
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error("ERRO: Variáveis de ambiente faltando no build de produção.");
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});